name: momnjo_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3
  http: ^0.13.3
  shared_preferences: ^2.0.6
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.8
  connectivity_plus: ^5.0.2
  intl: ^0.17.0
  salomon_bottom_bar: ^3.3.1
  cupertino_icons: ^1.0.8
  # flutter_app_badger: 1.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/momnjo_logo.png
    - assets/banner1.png
    - assets/banner2.png
    - assets/banner3.png
    - assets/promo.png
    - assets/darmawangsa.png
    - assets/txt-branches.png
    - assets/home-service.png
    - assets/txt-recommended-service.png
    - assets/kid.png
    - assets/mom2be.png
    - assets/after-labour.png
    - assets/baby-massage.png
    - assets/him-her.png
    - assets/youtube.png
    - assets/txt-video-treatment.png
    - assets/bookbg.png
    - assets/wa.png
